### ISSUE TITLE
Allow get_mut despite custom weight scale

### ISSUE THREAD

**Issue by mattfbacon** [marmeladema/clru-rs#52]
If the modification will not change the weight I see no reason to prevent mutable access just because there is a weight scale.

I understand the basic motivation but it makes it impossible to use the crate for my intended use. I don't want or need the overhead of interior mutability.

**Comment by marmeladema** [comment]
Hi and thank you for looking into this crate :)

I see two ways to solve your use case without introducing error prone methods:
1. Use `pop` to extract the value, modify it, and then `put` to insert it back
2. I believe we could add an `update` method that would take a closure `FnOnce(&mut T)` to modify in place a value. That method however need to panic if the weight has changed. I will look into this one because it seems like a nice addition.

**Comment by mattfbacon** [comment]
BTW, I realized that I was doing something wrong and refactored. I'm happily using your crate :)

1 seems like a good option. The only thing I wonder about is how it will affect the LRU aspect. I know that the getters update the LRU status of the entry. Would pop and put have the same effect? Any small differences?

**Comment by marmeladema** [comment]
It should not have any semantic difference as get_mut is moving the accessed element to the front of the cache, as well as put which insert at the top.
Additionally, allocated memory is preserved.
The only difference is the double access to the cache, which for performance sensitive work flow might be suboptimal.

**Comment by mattfbacon** [comment]
Ok, makes sense. In that case I think this isn't really an issue.
